account/urls.py
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.register_view, name="register_view"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view")
]

get_authy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("account.urls", namespace="account"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models


class Dictionary(models.Model):
    file = models.FileField(upload_to='files/')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Dictionaries"

account/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class RegisterForm(forms.Form):

    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    password1 = forms.CharField(
        widget=forms.PasswordInput,
        label="Password"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput,
        label="Confirm password"
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)
        # The iexact makes the query responed to case insensitive

        if qs.exists():
            # exists method return a bool if or not if the query exist in the DB.
            raise forms.ValidationError(
                "Username is invalid, please pick another."
            )
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)
        # The iexact makes the query responed to case insensitive

        if qs.exists():
            # exists method return a bool if or not if the query exist in the DB.
            raise forms.ValidationError(
                "Email already in use, please pick another."
            )
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    "Passwords don't match"
                )
        return password2


class LoginForm(forms.Form):

    username = forms.CharField(max_length=50)
    password = forms.CharField(
        widget=forms.PasswordInput
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)
        # The iexact makes the query responed to case insensitive

        if not qs.exists():
            # exists method return a bool if or not if the query exist in the DB.
            raise forms.ValidationError(
                "Username is invalid."
            )

        return username


class searchForm(forms.Form):
    search = forms.CharField(max_length=50, label="Search Word")

account/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import LoginForm, RegisterForm, searchForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, get_user
from . models import Dictionary
from difflib import get_close_matches
import json

User = get_user_model()


def index(request, *args, **kwargs):
    return render(
        request,
        "base.html"
    )


def register_view(request, *args, **kwargs):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            password2 = form.cleaned_data.get("password2")
            # Don't print out the password as a decent dev

            try:

                user = User.objects.create_user(
                    username=username,
                    email=email,
                    first_name=first_name,
                    last_name=last_name,
                    password=password2
                )
            except:
                user = None

            if user:
                login(request, user)
                return redirect("account:dashboard")
            else:
                request.session["register_error "] = 1  # True

    return render(request,
                  "registration.html", dict(
                      form=form
                  )
                  )


def login_view(request, *args, **kwargs):

    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():

            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            # Don't print out the password as a decent dev

            # print(request.session.items())
            user = authenticate(
                request,
                username=username,
                password=password
            )

            if user:
                # also check if user is_active...
                login(request, user)
                session = request.session
                session["name"] = request.user.username
                # print(session.items())

                return redirect("account:dashboard")
            else:
                request.session["invalid_user"] = 1

    return render(request,
                  "login_view.html", dict(
                      form=form
                  )
                  )


@login_required
def dashboard(request, *args, **kwargs):

    # dictionary = Dictionary.objects.get(pk=1)
    dictionary = get_object_or_404(Dictionary, pk=1)
    data = json.load(open(dictionary.file.path))
    name = request.user

    form_ser = searchForm()
    word_searched = None
    word_searched_list = None
    word_searched_str = 'What your search appears here'

    context = {"word_searched_list": word_searched_list,
               "word_searched_str": word_searched_str,
               "form_ser": form_ser, "name": name}

    if request.method == "POST":
        form_ser = searchForm(request.POST)

        if form_ser.is_valid():
            search = form_ser.cleaned_data.get("search")

            close_match = get_close_matches(
                search, data.keys(),
                n=5, cutoff=0.8
            )

            if search in data:
                word_searched = data[search]

            elif close_match:
                word_searched = f'Do you mean {close_match[0]} instead?'

            else:
                word_searched = "What you searched does not exist"

            if isinstance(word_searched, list):
                word_searched_list = word_searched
            else:
                word_searched_str = word_searched

            context = {"word_searched_list": word_searched_list,
                       "word_searched_str": word_searched_str,
                       "form_ser": form_ser, "name": name}

            return render(request, "dashboard.html", context)

    return render(request, "dashboard.html", context)


@ login_required
def logout_view(request):
    logout(request)
    # print(request.session.items())
    # request.user == AnonymousUser
    return redirect("account:index")

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index</title>

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css" rel="stylesheet" />
  <!-- online iinks -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>

<body>
  <header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'account:index' %}">
            <img src="{% static '/logo.png' %}" height="15" alt="" loading="lazy" />
          </a>
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'account:logout_view' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a {% block login_active %}{% endblock %} href="{% url 'account:login_view' %}">Login</a>
            </li>
            <li class="nav-item">
              <a {% block register_active %}{% endblock %} href="{% url 'account:register_view' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
          <form class="d-flex input-group w-auto">
            <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
              aria-describedby="search-addon" />
            <span class="input-group-text text-white border-0" id="search-addon">
              <i class="fas fa-search"></i>
            </span>
          </form>
          <!-- Avatar -->
          <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuLink"
            role="button" data-mdb-toggle="dropdown" aria-expanded="false">
            <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-circle" height="25" alt=""
              loading="lazy" />
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="{% url 'account:dashboard' %}">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Settings</a>
            </li>
            {% if user.is_authenticated %}
            <li>
              <a class="dropdown-item" href="{% url 'account:logout_view' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a class="dropdown-item" href="{% url 'account:login_view' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
  </header>
  <!-- Navbar -->

  <main class="main">
    <div class="container">

      {% block content %}
      
      {% endblock %}
    </div>
  </main>

  <!-- Footer -->
  <footer class="text-center text-lg-start text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="company">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="{% url 'admin:index' %}" class="text-reset">Admin</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> Oyo state, University of Ibadan, Ibadan</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              olaisaiah@gmail.com
            </p>
            <p><i class="fas fa-phone me-3"></i> +234 903 6240 993</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>

</html>

templates/dashboard.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <h1 class="text-dark my-2">DICTIONARY APP</h1>
    <h1 class="text-light text-center my-5">Welcome to your page <b class="text-warning">{{ name | title }}</b></h1>
    <div class="col my-3 text-secondary">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form_ser.as_p }}
            <input type="submit" value="Search">
        </form>
    </div>
    <div class="col text-success my-3">
        {% if word_searched_list %}
        {% for ser in word_searched_list %}
        <ul>
            <h3>
                <b>
                    <li>{{ ser }}</li>
                </b>
            </h3>
        </ul>
        {% endfor %}
        {% else %}
        <ul>
            <h3>
                <b>
                    <li>{{ word_searched_str }}</li>
                </b>
            </h3>
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/login_view.html
{% extends 'base.html' %}


{% block login_active %}
class="nav-link active"

{% endblock %}

{% block content %}
<div class="row my-5">
    <div class="col">
        <form action="{% url 'account:login_view' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form>
    </div>
</div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block register_active %}
class="nav-link active"
{% endblock %}

{% block content %}
<div class="row my-5">
    <div class="col">
        <form action="{% url 'account:register_view' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign in">
        </form>
    </div>
</div>
{% endblock %}